### ISSUE TITLE
unify output renderrer (json, terminal, ...)

### ISSUE THREAD

**Issue by mpavlase** [rfmvh/perfevents-result-collector#11]
write some class to standardize output of database queries. Consider these output formats:

- CVS (comma value separator)
- terminal friendly (tabs as separator i.e.)

Input is database query, output depends on selected format.

**Comment by mpavlase** [comment]
@rfmvh, do we need an option to print out CVS header, or print it always?

**Comment by frozenstein** [comment]
Let's print CSV header "always". I don't think it any header-enablement option would be useful for now. We can always grep it out by `grep -v -P '^#' `...

**Comment by ocasek** [comment]
Now every time is printed CSV header plus.
I have added option for printing data in table, you just need to add --table and you don't need any external library. It's added just for queries with multiple columns.

**Comment by mpavlase** [comment]
already implemented.
