### ISSUE TITLE
put printing logic into format_data if it's possible

### ISSUE THREAD

**Issue by mpavlase** [rfmvh/perfevents-result-collector#15]
https://github.com/rfmvh/perfevents-result-collector/blob/68e5fbedb6e6a513c1d851abe16d866396dd1e75/perfresultcollector/show-results.py#L67-L74

Other notes:
 * please try to be consistent for name convention, such as `clmn` in `format_data.py` Rest of all variables has full English name (without abbreviation)
* rename the method `type_of_log` to something more descriptive - it's too general to get an idea what it does. It matters a lot, because code (in general) is more often read (also by others) than written. Keep that in mind.

**Comment by ocasek** [comment]
643868291

**Comment by ocasek** [comment]
6e56bd8

**Comment by mpavlase** [comment]
looks good
