### ISSUE TITLE
review dbinterface

### ISSUE THREAD

**Issue by mpavlase** [rfmvh/perfevents-result-collector#16]
There is no need to using parentheses
https://github.com/rfmvh/perfevents-result-collector/blob/d7fc30f79223c38601757aa5937cb17df6a382db/perfresultcollector/dbinterface.py#L31

Dry run for select query should return actual results, because this operation can't modify actual data
https://github.com/rfmvh/perfevents-result-collector/blob/d7fc30f79223c38601757aa5937cb17df6a382db/perfresultcollector/dbinterface.py#L52-L54

Put name to the logger (use `__name__` variable)
https://github.com/rfmvh/perfevents-result-collector/blob/d7fc30f79223c38601757aa5937cb17df6a382db/perfresultcollector/dbinterface.py#L17

**Comment by ocasek** [comment]
5078255

**Comment by mpavlase** [comment]
https://github.com/rfmvh/perfevents-result-collector/commit/5078255db8c768ec7bb8f860d91a0462c59aa536#diff-faf4e075e6c1ef61e82644fea1cb2d5bR53
