### ISSUE TITLE
review add-experiement

### ISSUE THREAD

**Issue by mpavlase** [rfmvh/perfevents-result-collector#17]
rename `systWide` to `system_wide` (use _ to join words in variable name, read pep8 about naming conventions)
https://github.com/rfmvh/perfevents-result-collector/blob/d7fc30f79223c38601757aa5937cb17df6a382db/perfresultcollector/add-experiment.py#L24

`else` is not necessary, if there is missing name, it will not continue anyway.
https://github.com/rfmvh/perfevents-result-collector/blob/d7fc30f79223c38601757aa5937cb17df6a382db/perfresultcollector/add-experiment.py#L27-L29

Same for "force" + use logging module to let user know that something goes wrong
https://github.com/rfmvh/perfevents-result-collector/blob/d7fc30f79223c38601757aa5937cb17df6a382db/perfresultcollector/add-experiment.py#L42-L47

Wrap long lines (there exists pep8 recommendation for this, 80 chars per line)
https://github.com/rfmvh/perfevents-result-collector/blob/d7fc30f79223c38601757aa5937cb17df6a382db/perfresultcollector/add-experiment.py#L37
same here
https://github.com/rfmvh/perfevents-result-collector/blob/d7fc30f79223c38601757aa5937cb17df6a382db/perfresultcollector/add-experiment.py#L49

run `add` function only when it's called via CLI
https://github.com/rfmvh/perfevents-result-collector/blob/d7fc30f79223c38601757aa5937cb17df6a382db/perfresultcollector/add-experiment.py#L54

**Comment by ocasek** [comment]
46726958ebbd

**Comment by mpavlase** [comment]
check comments here:
https://github.com/rfmvh/perfevents-result-collector/commit/46726958ebbdf8d9aa4443ae63f46154e67bbf68

**Comment by mpavlase** [comment]
finished, closing
