### ISSUE TITLE
review show-* scripts - common patterns

### ISSUE THREAD

**Issue by mpavlase** [rfmvh/perfevents-result-collector#19]
I've found these same patterns in several files, such as show_environments, show-experiments etc.

Open DB connection only when show_events function is called. Otherwise it would be executed if you try to import the file.
https://github.com/rfmvh/perfevents-result-collector/blob/d7fc30f79223c38601757aa5937cb17df6a382db/perfresultcollector/show-events.py#L20-L25

The condition is always true - you are iterating over keys and test if the key exists in the same dict:
https://github.com/rfmvh/perfevents-result-collector/blob/d7fc30f79223c38601757aa5937cb17df6a382db/perfresultcollector/show-kernels.py#L26-L28

**Comment by ocasek** [comment]
ddc2922

**Comment by mpavlase** [comment]
finished, closing...
