### ISSUE TITLE
Ensure python3 compatibility

### ISSUE THREAD

**Issue by rfmvh** [rfmvh/perfevents-result-collector#32]
This is a placeholder for Python 3 compatibility fix. We need this program to run on Python 3.x while keeping Python-2.7 compatibility.

**Comment by frozenstein** [comment]
Branch for this: py3compat (branched from already merged develop+master, so prepared)
Currently, only visible problem is "print line"...

**Comment by rfmvh** [comment]
Fixed by commits 06595735ed06edd66dd62ea1ed811db3b6dcca62 and ed5e9676e2feb3b24ad9a3945bf18dad5241ef62
