### ISSUE TITLE
[RFE] add DEBUG MODE

### ISSUE THREAD

**Issue by frozenstein** [rfmvh/perfevents-result-collector#4]
The `DBConnection` class methods `query` (and `select`) offer Debug boolean parameter, which defaults to `False`. When `True`, it prints out all the DB queries when sent to DB. We currently do not have any mean to enable that. Either `--debug` option or an env variable like `DEBUG=1` might enable debugmode, so Debug would be `True` and queries would be printed.

**Comment by ocasek** [comment]
For show-* its done in 5d08bb01c2ae18 
Should I add this feature in other scripts?

**Comment by mpavlase** [comment]
Yes, I think that would be beneficial to have this option available anywhere it will make sense.

**Comment by frozenstein** [comment]
Especially the import-results tool needs it, since the imports fail sometimes and it would be great to know why.
