### ISSUE TITLE
[RFE] allow multiple options of same type in rcl-show-results

### ISSUE THREAD

**Issue by frozenstein** [rfmvh/perfevents-result-collector#5]
The `rcl-show-results` tool offers various command-line switches to filter the search. Such as `--event=CYCLES`. It would be great if multiple instances of an option were allowed, like: `--event=CYCLES --event=cpu-cycles`. There are events with multiple names (one event has two or more names), so it would be great to enable add the criteria. Also, CPU microarches need to be added up, such as `--cpu-microarch=IVB --cpu-microarch=IVB-EP`; IVB and IVB-EP are very similar processor microarchitectures, thus it makes sense to review their results together.

**Comment by ocasek** [comment]
940f24eb564b82bf

**Comment by frozenstein** [comment]
Seems working. Thanks.
