### ISSUE TITLE
update hashbang line

### ISSUE THREAD

**Issue by mpavlase** [rfmvh/perfevents-result-collector#9]
... to `/usr/bin/env python` Otherwise it wouldn't work properly with virtualenv.

**Comment by mpavlase** [comment]
dbinterface.py shouldn't be callable (set execute bit permission + hashbang line), same as models.py

**Comment by ocasek** [comment]
f708d58

**Comment by mpavlase** [comment]
+ models also aren't executable

**Comment by mpavlase** [comment]
verified, closing
